
# 频道配置文件
CHANNELS = {
    # 央视频道 - 使用央视官网EPG页面
    "CCTV1": {"name": "CCTV-1 综合", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv1"], "source": "cctv"},
    "CCTV2": {"name": "CCTV-2 财经", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv2"], "source": "cctv"},
    "CCTV3": {"name": "CCTV-3 综艺", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv3"], "source": "cctv"},
    "CCTV4": {"name": "CCTV-4 中文国际", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv4"], "source": "cctv"},
    "CCTV5": {"name": "CCTV-5 体育", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv5"], "source": "cctv"},
    "CCTV5+": {"name": "CCTV-5+ 赛事", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program/CCTV-CCTV5-plus-w1.html", "https://www.epg.net.cn/cctv5plus"], "source": "cctv"},
    "CCTV6": {"name": "CCTV-6 电影", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv6"], "source": "cctv"},
    "CCTV7": {"name": "CCTV-7 国防军事", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv7"], "source": "cctv"},
    "CCTV8": {"name": "CCTV-8 电视剧", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv8"], "source": "cctv"},
    "CCTV9": {"name": "CCTV-9 纪录", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv9"], "source": "cctv"},
    "CCTVjilu": {"name": "CCTV-9 纪录", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv9"], "source": "cctv"},
    "CCTV10": {"name": "CCTV-10 科教", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv10"], "source": "cctv"},
    "CCTV11": {"name": "CCTV-11 戏曲", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv11"], "source": "cctv"},
    "CCTV12": {"name": "CCTV-12 社会与法", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv12"], "source": "cctv"},
    "CCTV13": {"name": "CCTV-13 新闻", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv13"], "source": "cctv"},
    "CCTV14": {"name": "CCTV-14 少儿", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv14"], "source": "cctv"},
    "CCTV15": {"name": "CCTV-15 音乐", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv15"], "source": "cctv"},
    "CCTV17": {"name": "CCTV-17 农业农村", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program_satellite/-w1.html", "https://www.epg.net.cn/cctv17"], "source": "cctv"},
    "CCTVplus": {"name": "CCTV-5+ 赛事", "url": "https://tv.cctv.com/epg/", "backup_urls": ["https://www.tvmao.com/program/CCTV-CCTV5-plus-w1.html", "https://www.epg.net.cn/cctv5plus"], "source": "cctv"},
    
    # 主要卫视频道
    "HunanTV": {"name": "湖南卫视", "url": "https://www.hunantv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HNTV1-w1.html", "https://www.epg.net.cn/hunantv"], "source": "satellite"},
    "ZhejiangTV": {"name": "浙江卫视", "url": "https://www.zjtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/ZJTV1-w1.html", "https://www.epg.net.cn/zhejiangtv"], "source": "satellite"},
    "JiangsuTV": {"name": "江苏卫视", "url": "https://www.jstv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/JSTV1-w1.html", "https://www.epg.net.cn/jiangsutv"], "source": "satellite"},
    "DragonTV": {"name": "东方卫视", "url": "https://www.dragontv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/DFWS1-w1.html", "https://www.epg.net.cn/dragontv"], "source": "satellite"},
    "BeijingTV": {"name": "北京卫视", "url": "https://www.btv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/BTV1-w1.html", "https://www.epg.net.cn/beijingtv"], "source": "satellite"},
    "GuangdongTV": {"name": "广东卫视", "url": "https://www.gdtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/GDTV1-w1.html", "https://www.epg.net.cn/guangdongtv"], "source": "satellite"},
    "ShenzhenTV": {"name": "深圳卫视", "url": "https://www.sztv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/SZTV1-w1.html", "https://www.epg.net.cn/shenzhentv"], "source": "satellite"},
    "AnhuiTV": {"name": "安徽卫视", "url": "https://www.ahtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/AHTV1-w1.html", "https://www.epg.net.cn/anhuitv"], "source": "satellite"},
    "ShandongTV": {"name": "山东卫视", "url": "https://www.sdws.tv/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/SDTV1-w1.html", "https://www.epg.net.cn/shandongtv"], "source": "satellite"},
    "TianjinTV": {"name": "天津卫视", "url": "https://www.tjtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/TJTV1-w1.html", "https://www.epg.net.cn/tianjintv"], "source": "satellite"},
    
    # 各省卫视频道
    "HebeiTV": {"name": "河北卫视", "url": "https://www.hebtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HEBTV1-w1.html", "https://www.epg.net.cn/hebeitv"], "source": "satellite"},
    "ShanxiTV": {"name": "山西卫视", "url": "https://www.sxtvs.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/SXTV1-w1.html", "https://www.epg.net.cn/shanxitv"], "source": "satellite"},
    "InnerMongoliaTV": {"name": "内蒙古卫视", "url": "https://www.nmtv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/NMTV1-w1.html", "https://www.epg.net.cn/innermongoliatv"], "source": "satellite"},
    "LiaoningTV": {"name": "辽宁卫视", "url": "https://www.lntv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/LNTV1-w1.html", "https://www.epg.net.cn/liaoningtv"], "source": "satellite"},
    "JilinTV": {"name": "吉林卫视", "url": "https://www.jlntv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/JLTV1-w1.html", "https://www.epg.net.cn/jilintv"], "source": "satellite"},
    "HeilongjiangTV": {"name": "黑龙江卫视", "url": "https://www.hljtv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HLJTV1-w1.html", "https://www.epg.net.cn/heilongjiangtv"], "source": "satellite"},
    "ShanghaiTV": {"name": "上海卫视", "url": "https://www.dragontv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/DFWS1-w1.html", "https://www.epg.net.cn/shanghaitv"], "source": "satellite"},
    "JiangxiTV": {"name": "江西卫视", "url": "https://www.jxtv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/JXTV1-w1.html", "https://www.epg.net.cn/jiangxitv"], "source": "satellite"},
    "HenanTV": {"name": "河南卫视", "url": "https://www.hntv.tv/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HNTV1-w1.html", "https://www.epg.net.cn/henantv"], "source": "satellite"},
    "HubeiTV": {"name": "湖北卫视", "url": "https://www.hbtv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HUBTV1-w1.html", "https://www.epg.net.cn/hubeitv"], "source": "satellite"},
    "HunanTV2": {"name": "湖南卫视", "url": "https://www.hunantv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HNTV1-w1.html", "https://www.epg.net.cn/hunantv"], "source": "satellite"},
    "GuangxiTV": {"name": "广西卫视", "url": "https://www.gxtv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/GXTV1-w1.html", "https://www.epg.net.cn/guangxitv"], "source": "satellite"},
    "HainanTV": {"name": "海南卫视", "url": "https://www.hntv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/HNTV1-w1.html", "https://www.epg.net.cn/hainantv"], "source": "satellite"},
    "FujianTV": {"name": "东南卫视", "url": "https://www.fjtv.net/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/FJTV2-w1.html", "https://www.epg.net.cn/fujiantv"], "source": "satellite"},
    "ChongqingTV": {"name": "重庆卫视", "url": "https://www.cqtv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/CQTV1-w1.html", "https://www.epg.net.cn/chongqingtv"], "source": "satellite"},
    "SichuanTV": {"name": "四川卫视", "url": "https://www.sctv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/SCTV1-w1.html", "https://www.epg.net.cn/sichuantv"], "source": "satellite"},
    "GuizhouTV": {"name": "贵州卫视", "url": "https://www.gzstv.com/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/GZTV1-w1.html", "https://www.epg.net.cn/guizhoutv"], "source": "satellite"},
    "YunnanTV": {"name": "云南卫视", "url": "https://www.yntv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/YNTV1-w1.html", "https://www.epg.net.cn/yunnantv"], "source": "satellite"},
    "TibetTV": {"name": "西藏卫视", "url": "https://www.xztv.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/XZTV1-w1.html", "https://www.epg.net.cn/tibettv"], "source": "satellite"},
    "ShaanxiTV": {"name": "陕西卫视", "url": "https://www.sxtv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/SXTV1-w1.html", "https://www.epg.net.cn/shaanxitv"], "source": "satellite"},
    "GansuTV": {"name": "甘肃卫视", "url": "https://www.gstv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/GSWST1-w1.html", "https://www.epg.net.cn/gansutv"], "source": "satellite"},
    "QinghaiTV": {"name": "青海卫视", "url": "https://www.qhtv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/QHTV1-w1.html", "https://www.epg.net.cn/qinghaitv"], "source": "satellite"},
    "NingxiaTV": {"name": "宁夏卫视", "url": "https://www.nxtv.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/NXTV1-w1.html", "https://www.epg.net.cn/ningxiatv"], "source": "satellite"},
    "XinjiangTV": {"name": "新疆卫视", "url": "https://www.xjtvs.com.cn/epg", "backup_urls": ["https://www.tvmao.com/program_satellite/XJTV1-w1.html", "https://www.epg.net.cn/xinjiangtv"], "source": "satellite"}
}
